### ISSUE TITLE
Suggestion: add a way for users to reset their highscore

### ISSUE THREAD

**Issue by Pinglet** [DingusPingus/CS476-Speedrun-Project#1]
My brother uses the same computer as me and my highscore is really good and there is no way for him to beat it. Would it be possible to add a way to reset our highscore so that They could have a chance of beating their own score and not my insanely good one?

**Comment by Pinglet** [comment]
There is currently a way for you to do this by opening up devtools through a browser like Chrome with F12 key. Navigate to the application tab, Storage section on the left, and under the IndexedDB, /idbfs/FILE_DATA  just right click delete the key that has "PlayerPrefs" in its name. This should delete your local data and allow you to set a new highscore.  However, we could develop a way to have this functionality built into the game and therefore improve the user experience if desired.

**Comment by PsytruK** [comment]
Implemented a button that can be clicked within the options menu to reset the high scores for both of the current levels.
